### ISSUE TITLE
FOLIT

### ISSUE THREAD

**Issue by tomByrer** [serverless/blog#103]
"Flash of Lorium Ipsum Text"
When initially loading the blog route, I got a page full of lorium Ipsum text, then a server error, then an error page, then a redirect to the actual live blog.
FireFox dev nightly & Chrome current on Win10, T1 over good WiFI.

I'd assume 'serverless' web pages would be prerendered as static pages with real data, or at least 'above the fold' is prerendered, & more is loaded after the initial.

**Comment by DavidWells** [comment]
The lorum text is a placeholder until the data loads. I might swap it out with loading text like seen on individual posts.

As for the error pages, I can't reproduce this. Can you shoot a quick video/gif of what you are seeing?

Thanks for the report!
