### ISSUE TITLE
Code snippets are displayed with light background and text

### ISSUE THREAD

**Issue by dhavall08** [serverless/blog#1039]
Open up any blog of the serverless site, the background of code snippets looks different than normal. It shows code in the light background and white texts. Ex. [One of the blog](https://www.serverless.com/blog/strategies-implementing-user-authentication-serverless-applications).

**Comment by stevenyix** [comment]
Thanks for reporting this.  We are tracking this down to fix asap.

**Comment by dhavall08** [comment]
Thanks. Looks like, this has been fixed but similar to that, the **em** tag isn't really emphasized due to light text. (Attached image). Actually, this is a very minor edit, which I can try to update but I couldn't be able to find the editable page link on Github. Let me know if that code is open source.

![blog em tag issue](https://user-images.githubusercontent.com/24195703/146523418-b02919be-7bf0-40e3-98b6-32b14fc4bf93.png)

**Comment by stevenyix** [comment]
Thanks again! I logged this issue with our web team to address it.  Appreciate you offering to help out, but our front-end website and blog is on a hosted platform and isn't open-source.

**Comment by stevenyix** [comment]
@dhavall08 we've updated the website to make the <em> tag more readable. Thanks again and have a great holiday!

**Comment by dhavall08** [comment]
Thanks @stevenyix for the update. Have a great holiday to you too.
