### ISSUE TITLE
Office Hours Thumbnail

### ISSUE THREAD

**Issue by Stefmonge** [serverless/blog#11]
![office hours](https://cloud.githubusercontent.com/assets/20538501/19769976/25c14630-9c23-11e6-9698-8cda3b8809d8.jpg)

**Comment by Rystakei** [comment]
🙈 Sorry Rystakei, you aren't authorized to schedule posts.

You must be a collaborator on this repository to schedule posts.

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by Rystakei** [comment]
🙈 Sorry Rystakei, you aren't authorized to schedule posts.

You must be a collaborator on this repository to schedule posts.

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)
