### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by j0k3r** [serverless/blog#153]
I forked the blog repo thinking it was a simple jekyll website but it's not. And it seems more complicated than I thought to add a page which is not a text.

Anyway, I think it could be useful if the blog has a RSS feed ! Like `https://serverless.com/blog/index.xml` or `https://serverless.com/blog/rss.xml`

**Comment by j0k3r** [comment]
Ok I found the feed but it wasn't discoverable in the html page.

**Comment by Birowsky** [comment]
so.. um.. where is the feed? WHERE IS THE FEED!!!

**Comment by j0k3r** [comment]
@Birowsky the feed is https://serverless.com/blog/feed.xml

**Comment by Birowsky** [comment]
Thank you ^_^

**Comment by steveroot** [comment]
Maybe something is broken, https://serverless.com/blog/feed.xml == 404 error

**Comment by j0k3r** [comment]
The feed is back https://github.com/serverless/site/pull/347#event-1895897524
