### ISSUE TITLE
How to add image (screen shot) in blog?

### ISSUE THREAD

**Issue by ozbillwang** [serverless/blog#454]
As title, if I want to add several screen shots in blog, how to add?

Review the exist blog, they use the s3 link, but how to know the link for the image I will upload.

**Comment by alexdebrie** [comment]
Hey @ozbillwang, is your image uploaded anywhere currently? If so, you can just use the link with the following syntax:

```
![<Alt text>](https://link.to.my/image)
```

Does that help?

**Comment by ozbillwang** [comment]
So i can’t push the image into repo directly and reference from github?

**Comment by alexdebrie** [comment]
<img width="840" alt="screen shot 2017-12-16 at 6 42 01 am" src="https://user-images.githubusercontent.com/6509926/34070461-49a115f8-e22c-11e7-8015-8dd0d7701eae.png">

You can cheat a bit and use GitHub's CDN 😄 . Choose to upload an image and it will spit out the necessary HTML, including a URL where the image is located:

<img width="810" alt="screen shot 2017-12-16 at 11 43 26 am" src="https://user-images.githubusercontent.com/6509926/34073017-6f3943ba-e256-11e7-80c7-fdf52c1acf00.png">
